# Generated by Django 4.2.9 on 2026-02-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id_tache', models.CharField(db_column='id_tache', max_length=255, primary_key=True, serialize=False)),
                ('id_client', models.CharField(blank=True, db_column='id_client', max_length=255, null=True)),
                ('titre_tache', models.CharField(db_column='titre_tache', max_length=255)),
                ('description_tache', models.TextField(blank=True, db_column='description_tache', null=True)),
                ('date_debut', models.DateTimeField(db_column='date_debut')),
                ('date_echeance', models.DateTimeField(blank=True, db_column='date_echeance', null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], db_column='statut', default='en_attente', max_length=50)),
                ('couleur_tache', models.CharField(blank=True, db_column='couleur_tache', max_length=50, null=True)),
                ('affecter_a', models.CharField(blank=True, db_column='affecter_a', max_length=255, null=True)),
                ('effacer', models.BooleanField(db_column='effacer', default=False)),
                ('sync', models.BooleanField(db_column='sync', default=False)),
                ('date_synchro', models.DateTimeField(blank=True, db_column='date_synchro', null=True)),
                ('date_enreg', models.DateTimeField(auto_now_add=True, db_column='date_enreg')),
                ('date_modif', models.DateTimeField(auto_now=True, db_column='date_modif')),
                ('idutilisateur_save', models.CharField(blank=True, db_column='idutilisateur_save', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tache',
                'ordering': ['-date_debut'],
                'managed': True,
            },
        ),
    ]
