# Generated by Django 4.2.9 on 2026-02-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apporteur',
            fields=[
                ('code_apporteur', models.CharField(db_column='ID_Commercial', max_length=255, primary_key=True, serialize=False, verbose_name='Référence')),
                ('nom_apporteur', models.CharField(db_column='Nom_Raison_Sociale', max_length=255, verbose_name='Nom / Raison Sociale')),
                ('type_apporteur', models.CharField(db_column='Type_Commercial', max_length=255, verbose_name='Type')),
                ('adresse', models.CharField(blank=True, db_column='Adresse', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, db_column='Telephone', max_length=255, null=True)),
                ('date_naissance', models.DateField(blank=True, db_column='Date_naissance', null=True)),
                ('nif_rccm', models.CharField(blank=True, db_column='NIF_RCCM', max_length=255, null=True, verbose_name='NIF / RCCM')),
                ('num_piece_identite', models.CharField(blank=True, db_column='Numero_Piece_Identite', max_length=255, null=True)),
                ('date_entree', models.DateField(blank=True, db_column='Date_Embauche', null=True, verbose_name="Date d'entrée en relation")),
                ('frequence_paiement', models.CharField(blank=True, choices=[('Mensuel', 'Mensuel'), ('Trimestriel', 'Trimestriel'), ('Semestriel', 'Semestriel'), ('Annuel', 'Annuel')], db_column='Frequence_paiement', max_length=50, null=True)),
                ('login', models.CharField(blank=True, db_column='login_commercial', max_length=255, null=True)),
                ('mot_de_passe', models.CharField(blank=True, db_column='mdp_commercial', max_length=255, null=True)),
                ('effacer', models.BooleanField(db_column='effacer', default=False)),
                ('date_enreg', models.DateTimeField(auto_now_add=True, db_column='date_enreg', null=True)),
            ],
            options={
                'verbose_name': 'Apporteur',
                'verbose_name_plural': 'Apporteurs',
                'db_table': 'commerciaux',
                'ordering': ['nom_apporteur'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionApporteur',
            fields=[
                ('id_commission', models.AutoField(db_column='IDCOMMISSIONS_COMMERCIAL', primary_key=True, serialize=False)),
                ('type_contrat', models.CharField(db_column='type_contrat', max_length=255, verbose_name='Type de contrat')),
                ('mode_remuneration', models.CharField(choices=[('fixe', 'Commission fixe'), ('pourcentage', 'Pourcentage')], db_column='mode_remuneration', default='pourcentage', max_length=50)),
                ('taux_commission', models.DecimalField(db_column='taux_commission', decimal_places=2, default=0, max_digits=5)),
                ('commission_fixe', models.IntegerField(db_column='commission_fixe', default=0)),
                ('effacer', models.BooleanField(db_column='effacer', default=False)),
                ('date_enreg', models.DateTimeField(auto_now_add=True, db_column='date_enreg')),
                ('code_apporteur', models.ForeignKey(db_column='code_apporteur', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='commerciaux.apporteur')),
            ],
            options={
                'verbose_name': 'Commission Apporteur',
                'managed': True,
            },
        ),
    ]
